name: Diffusion
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - albumentations==0.4.3
    - diffusers
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - invisible-watermark
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit==0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.19.2
    - torchmetrics==0.6.0
    - kornia==0.6
    - scikit-learn==1.1.1
    - requests==2.24.0
    # - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    # - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - blinker==1.9.0
    - certifi==2025.7.14
    - charset-normalizer==3.4.2
    - click==8.2.1
    - dotenv==0.9.9
    - filelock==3.18.0
    - Flask==3.1.1
    - flask-cors==6.0.1
    - fsspec==2025.7.0 
    - idna==3.10
    - tencentcloud-sdk-python-aiart==3.0.1425
    - tencentcloud-sdk-python-common==3.0.1425
    - typing_extensions==4.14.1
    - tzdata==2025.2
